In [4]:
import numpy as np

STUDENT_NAME = "Marv Inocencio"
STUDENT_ID = 351  # palitan mo ng actual ID mo (numbers lang)

np.random.seed(STUDENT_ID)

data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)

mean_val = np.mean(data)
std_val = np.std(data)

print("Mean:", mean_val)
print("Std Dev:", std_val)

Marv Inocencio's Array: [67 99 75 12 59 33 76 50 11 56]
Mean: 53.8
Std Dev: 26.865591376331174


In [6]:
import numpy as np

STUDENT_NAME = "Marv Inocencio"
STUDENT_ID = 351  # palitan mo ng actual ID mo (numbers lang)

np.random.seed(STUDENT_ID)

matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3, 4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)

row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)

print("Row sums:", row_sums)
print("Column sums:", col_sums)

Marv Inocencio's Matrix:
 [[ 3  3 11 12]
 [ 7 11  1 12]
 [18 11 17 16]]
Row sums: [29 31 62]
Column sums: [28 25 29 40]


In [7]:
import numpy as np

STUDENT_NAME = "Marv Inocencio"
STUDENT_ID = 351  # palitan mo ng actual ID mo

np.random.seed(STUDENT_ID)

arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3, 3, 3))
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)

slice_mid = arr3d[:, 1, :]
print("Slice[:,1,:]:\n", slice_mid)

Marv Inocencio's 3D Array:
 [[[ 2  2 10]
  [11  6 10]
  [ 0 11 17]]

 [[10 16 20]
  [15 14  1]
  [ 6  9  8]]

 [[ 8 11  0]
  [ 9  6 16]
  [12 11  8]]]
Slice[:,1,:]:
 [[11  6 10]
 [15 14  1]
 [ 9  6 16]]


In [8]:
import numpy as np

STUDENT_NAME = "Marv Inocencio"
STUDENT_ID = 351

np.random.seed(STUDENT_ID)

x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
filtered = x[(x > STUDENT_ID % 50) & (x < STUDENT_ID % 100)]

print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

Marv Inocencio's Original: [67 99 75 12 59 33 76 50 11 56]
Filtered subset: [12 33 50 11]


In [9]:
import numpy as np

STUDENT_NAME = "Marv Inocencio"
STUDENT_ID = 351

np.random.seed(STUDENT_ID)

A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2, 2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2, 2))

print("Matrix A:\n", A)
print("Matrix B:\n", B)

product = A @ B
det_A = np.linalg.det(A)

print("A @ B:\n", product)
print("Determinant of A:", det_A)

Matrix A:
 [[ 3  3]
 [11 12]]
Matrix B:
 [[ 7 11]
 [ 1 12]]
A @ B:
 [[ 24  69]
 [ 89 265]]
Determinant of A: 2.999999999999998


In [10]:
import numpy as np

STUDENT_NAME = "Marv Inocencio"
STUDENT_ID = 351

angles = np.linspace(0, 2*np.pi, 8)
sine_vals = np.sin(angles)
cos_vals = np.cos(angles)

print(f"{STUDENT_NAME}'s Angles:", angles)
print("Sine:", sine_vals)
print("Cosine:", cos_vals)

Marv Inocencio's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [11]:
import numpy as np

STUDENT_NAME = "Marv Inocencio"
STUDENT_ID = 351

np.random.seed(STUDENT_ID)

arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4, 4))
arr[::2, ::2] = 0

print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

Marv Inocencio's Modified 4x4 Array:
 [[ 0  3  0 12]
 [ 7 11  1 12]
 [ 0 11  0 16]
 [15  2  7 10]]


In [12]:
import numpy as np

STUDENT_NAME = "Marv Inocencio"
STUDENT_ID = 351

np.random.seed(STUDENT_ID)

scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)
grades = np.where(scores >= STUDENT_ID % 70, 'Pass', 'Fail')

print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)

Marv Inocencio's Scores: [66 98 74 11 58 32 75 49 10 55]
Grades: ['Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass']


In [13]:
import numpy as np

STUDENT_NAME = "Marv Inocencio"
STUDENT_ID = 351

np.random.seed(STUDENT_ID)

arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3, 4))
flat_arr = arr.flatten()
transposed_arr = arr.T

print("Original array:\n", arr)
print("Flattened:", flat_arr)
print("Transposed:\n", transposed_arr)

Original array:
 [[ 3  3 11 12]
 [ 7 11  1 12]
 [18 11 17 16]]
Flattened: [ 3  3 11 12  7 11  1 12 18 11 17 16]
Transposed:
 [[ 3  7 18]
 [ 3 11 11]
 [11  1 17]
 [12 12 16]]


In [14]:
import numpy as np

STUDENT_NAME = "Marv Inocencio"
STUDENT_ID = 351

np.random.seed(STUDENT_ID)

arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3, 3))
mask = arr % 2 == 0
arr[mask] = -1

print("Array with conditional replacements:\n", arr)

Array with conditional replacements:
 [[ 3  3 11]
 [-1  7 11]
 [ 1 -1 -1]]


In [16]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Marv Inocencio"
STUDENT_ID = 351

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'Name': [STUDENT_NAME] * 5,
    'Score': np.random.randint(STUDENT_ID % 50, STUDENT_ID % 100 + 50, 5),
    'YearsCodePro': np.random.randint(0, STUDENT_ID % 20 + 10, 5)
})

print(df)

             Name  Score  YearsCodePro
0  Marv Inocencio     67            10
1  Marv Inocencio     99             0
2  Marv Inocencio     75            11
3  Marv Inocencio     12            17
4  Marv Inocencio     59            10


In [17]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Marv Inocencio"
STUDENT_ID = 351

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'EdLevel': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()

print(avg_salary)

EdLevel
Bachelor    105086.0
Master       98394.0
PhD          78923.0
Name: ConvertedComp, dtype: float64


In [18]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Marv Inocencio"
STUDENT_ID = 351

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'Country': ['Philippines', 'USA', 'UK', 'Canada', 'Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

top5 = df.sort_values(by='ConvertedComp', ascending=False)

print(top5)

       Country  ConvertedComp
3       Canada         149626
4      Germany         133290
2           UK          78923
1          USA          63498
0  Philippines          60546


In [19]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Marv Inocencio"
STUDENT_ID = 351

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'Name': [STUDENT_NAME] * 5,
    'YearsCodePro': np.random.randint(0, STUDENT_ID % 20 + 10, 5)
})

high_exp = df[df['YearsCodePro'] > STUDENT_ID % 10]

print(high_exp)

             Name  YearsCodePro
0  Marv Inocencio             2
1  Marv Inocencio             2
2  Marv Inocencio            10
3  Marv Inocencio            11
4  Marv Inocencio             6


In [20]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Marv Inocencio"
STUDENT_ID = 351

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']

df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)

print(df)

   ConvertedComp   Bracket
0          60546   50-100k
1          63498   50-100k
2          78923   50-100k
3         149626  100-150k
4         133290  100-150k


In [22]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Marv Inocencio"
STUDENT_ID = 351

np.random.seed(STUDENT_ID)

# Corrected Code: Using a functional salary range (40000 to 150000)
df = pd.DataFrame({
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

df['LogComp'] = np.log(df['ConvertedComp'])

print(df)

   ConvertedComp    LogComp
0          60546  11.011159
1          63498  11.058764
2          78923  11.276228
3         149626  11.915894
4         133290  11.800282


In [23]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Marv Inocencio"
STUDENT_ID = 351

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'YearsCodePro': np.random.randint(0, STUDENT_ID % 20 + 10, 5),
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

corr_matrix = df.corr()

print(corr_matrix)

               YearsCodePro  ConvertedComp
YearsCodePro       1.000000      -0.764663
ConvertedComp     -0.764663       1.000000


In [24]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Marv Inocencio"
STUDENT_ID = 351

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'EdLevel': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# Calculate mean, median, and standard deviation for each 'EdLevel'
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean', 'median', 'std']).reset_index()

print(summary)

    EdLevel      mean    median           std
0  Bachelor  105086.0  105086.0  62989.072068
1    Master   98394.0   98394.0  49350.396473
2       PhD   78923.0   78923.0           NaN


In [25]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Marv Inocencio"
STUDENT_ID = 351

np.random.seed(STUDENT_ID)

# Generate salaries
df = pd.DataFrame({
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

threshold = 110000

# Create the 'HighPay' column using np.where()
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')

print(df)

   ConvertedComp HighPay
0          60546      No
1          63498      No
2          78923      No
3         149626     Yes
4         133290     Yes


In [26]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Marv Inocencio"
STUDENT_ID = 351

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'Country': ['Philippines', 'USA', 'UK', 'Canada', 'Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# Group by 'Country' and calculate the mean and max 'ConvertedComp'
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean', 'max'])

print(top_countries)

                 mean     max
Country                      
Canada       149626.0  149626
Germany      133290.0  133290
Philippines   60546.0   60546
UK            78923.0   78923
USA           63498.0   63498
